### ISSUE TITLE
Punctual reference in Estuary is out of date?

### ISSUE THREAD

**Issue by tedthetrumpet** [dktr0/Punctual#10]
None of the examples in the Punctual Reference in the browser work, eg `sin 440 => centre`

**Comment by dktr0** [comment]
This was in reference to the Punctual reference in Estuary and should now be fixed (I deleted a few entries there that were so out of date they were hard to quickly up date, and also added the URL of the official Punctual reference which is guaranteed to be as up-to-date as things come). Thanks for pointing this out!

**Comment by tedthetrumpet** [comment]
Great, glad this was useful :)
