### ISSUE TITLE
Missing the latest documentation? (e.g. for feedback)

### ISSUE THREAD

**Issue by totalgee** [dktr0/Punctual#13]
Hi there, I discovered Punctual through a workshop last week, and it seems really fun and interesting. However, I was wondering what functions I may be missing from the documentation? I know of several things, such as `fdbk` and `fb`, which don't appear in the [REFERENCE.md](https://github.com/dktr0/Punctual/blob/main/REFERENCE.md). Is there a recommended way in the code to "grep" for the list of current functions?

**Comment by dktr0** [comment]
There shouldn't be too much that is missing, and when prodded like this, I can usually quickly add it. I have just added fdbk and fb to the reference. A heads up that I consider fdbk deprecated and will likely remove it in the next major version (which is a significant focus of my time from Jan-Apr 2024 when I am on a research leave - I will also be rewriting Punctual from the ground up in PureScript, to enable it to be an Estuary exolang as well as probably for significant performance benefits...)

**Comment by dktr0** [comment]
PS - you may be interested to follow/participate in the Punctual discussion at the punctual channel #punctual on the Estuary Discord (current invite link is here: https://discord.gg/snvFzkPtFr)

**Comment by totalgee** [comment]
Great, thank you for the quick response! I've joined the Discord, too. 👍
