### ISSUE TITLE
Reference.md description of +- is incorrect

### ISSUE THREAD

**Issue by jamshark70** [dktr0/Punctual#2]
```
lpf (saw (23m)) (250 ~~ 350 $ sin 1) 10 * (-20) db >> left;
lpf (saw (23m)) (300 +- 50 $ sin 1) 10 * (-20) db >> right;
```

Why are these not the same? I might expect some phase shift on the modulator but the right channel seems totally wrong.

**Comment by jamshark70** [comment]
Oh, wait:

```
saw (midicps $ 24 +- 0.03 $ sin 1) >> centre; -- go between 3% below MIDI note 24 and 3% above

// and
(+-) :: Graph -> Graph -> Graph -> Graph
a +- b = modulatedRangeGraph (a - (a*b)) (a + (a*b))
```

But I was looking at the reference, which seems incorrect:

```
[centre] +- [offset] $ [input] -- bipolar (-1,1) input rescaled to range centre +- offset
```

Offset is really a scaler: `a +- 1` ranges 0 .. 2a.

I'll change the issue title, then.

**Comment by dktr0** [comment]
Do you think it's better if it says "scaled offset"?

**Comment by jamshark70** [comment]
> Do you think it's better if it says "scaled offset"?

Sure, with a couple of examples, like `[centre] +- [offsetRatio] $ [input] -- bipolar (-1,1) input rescaled to range centre +- (offsetRatio * centre), e.g. a +- 0.5 ranges from 0.5a to 1.5a`

hjh

**Comment by dktr0** [comment]
Done - thanks!
