### ISSUE TITLE
syntax error if comment ends with semicolon

### ISSUE THREAD

**Issue by sorenpeter** [dktr0/Punctual#3]
Hi dr. 0,

So found that commeting does not really works as one would except:
If you have a line of code, that you want to comment out, then Punctual will give you an error if you do not also remove the ending semicolon of that line:
No comments:
![Screenshot 2020-05-13 at 19 43 45](https://user-images.githubusercontent.com/8458421/81846495-791caa00-9552-11ea-9419-f9d4ef27a883.png)

Error when trying to make a comment, after removing the semicolon:
![Screenshot 2020-05-13 at 19 43 57](https://user-images.githubusercontent.com/8458421/81846497-7b7f0400-9552-11ea-9d60-368e15cdc0f0.png)

Comment accepted, but now you have to remember to add the semicolon if you want to use your code again:
![Screenshot 2020-05-13 at 19 44 09](https://user-images.githubusercontent.com/8458421/81846502-7de15e00-9552-11ea-90cc-f34f4cb8aaa9.png)

And it looks to be the same in Estuary:
![Screenshot 2020-05-13 at 19 49 58](https://user-images.githubusercontent.com/8458421/81846834-006a1d80-9553-11ea-9d46-bb22c183576c.png)

All the best
Søren Peter

**Comment by dktr0** [comment]
Thanks for submitting this to tracking! I've encountered this before but always forget to file it as a bug... Will try to fix in the next couple of days!

**Comment by dktr0** [comment]
Should be fixed now - both in standalone Punctual and Estuary.

**Comment by sorenpeter** [comment]
Yes seem to work now. Thank you:)
