### ISSUE TITLE
Variety of unexpected output with continuous functions on Intel UHD 620 graphics

### ISSUE THREAD

**Issue by cleary** [dktr0/Punctual#9]
Hi David, 
I've been preparing a demo for my workshop on my laptop and finding a significant number of unexpected things occurring with continuous functions.

I've verified the same issues are operating system independent, so I believe it's related to hardware not drivers:

1. `sin` behaves like saw
https://youtu.be/Vpp4NWBaqaM

2. `spin` with a time graph outputs to the entire screen space for a brief period every cycle, but then resets the spin so it doesn't complete a cycle
https://youtu.be/e3omnOFhIRE

**Comment by dktr0** [comment]
Interesting - thanks for reporting these. I can't reproduce either of those problems, which could make debugging a bit slow! Are you able to recreate the spin problem with literal numbers (and not a function of time)? And if so, do you have to use numbers of a certain magnitude to create the problem?

**Comment by cleary** [comment]
It seems like this has magically gone away ... bizarre.

I'll reopen if it appears again

**Comment by dktr0** [comment]
Huh! Stray cosmic particles?...
